[package]
name = "helios"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "cli",
    "client",
    "common",
    "config",
    "consensus",
    "execution",
    "helios-ts",
]

[dependencies]
client = { path = "./client" }
config = { path = "./config" }
common = { path = "./common" }
consensus = { path = "./consensus" }
execution = { path = "./execution" }

[patch.crates-io]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "c17c0c3c956f12d205a5ede3176599d8a30ca739" }

[patch."https://github.com/ralexstokes/ssz-rs"]
ssz-rs = { git = "https://github.com/ncitron/ssz-rs", branch = "fix-wasm" }
