[package]
name = "execution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
eyre = "0.6.8"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
hex = "0.4.3"
ssz-rs = { path = "../../ssz-rs/ssz-rs" }
blst = "0.3.10"
ethers = "1.0.0"
revm = { version = "2.3", default-features = false, features = ["std", "k256", "with-serde"] }
bytes = "1.2.1"
futures = "0.3.23"
toml = "0.5.9"
triehash-ethereum = { git = "https://github.com/openethereum/parity-ethereum", rev = "55c90d4016505317034e3e98f699af07f5404b63" }
async-trait = "0.1.57"
log = "0.4.17"
thiserror = "1.0.37"

common = { path = "../common" }
consensus = { path = "../consensus" }
