[package]
name = "consensus"
version = "0.2.0"
edition = "2021"

[dependencies]
eyre = "0.6.8"
futures = "0.3.23"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
hex = "0.4.3"
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "d09f55b4f8554491e3431e01af1c32347a8781cd" }
milagro_bls = { git = "https://github.com/Snowfork/milagro_bls" }
ethers = "1.0.0"
bytes = "1.2.1"
toml = "0.5.9"
async-trait = "0.1.57"
log = "0.4.17"
chrono = "0.4.22"
thiserror = "1.0.37"
reqwest = { version = "0.11.13", features = ["json"] }
discv5 = { version = "0.1.0", optional = true }
# TODO: only import the necessary features
libp2p = { version = "0.50.0", features = ["full"]}
tree_hash = { version = "0.4.0", optional = true }
tree_hash_derive = { version = "0.4.0", optional = true }
ssz-rs-derive = { git = "https://github.com/ralexstokes/ssz-rs", rev = "d09f55b4f8554491e3431e01af1c32347a8781cd", optional = true }

common = { path = "../common" }
config = { path = "../config" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-timer = "0.2.5"

[features]
p2p = [
    "dep:discv5", 
    "dep:tree_hash",
    "dep:tree_hash_derive",
    "dep:ssz-rs-derive",
]

